Repository blink1073/oct2py, pull requests merged in 2022-03, with the labels that each got.

#226 Handle warnings
  .coveragerc
  .github/workflows/tests.yml
  .pre-commit-config.yaml
  CONTRIBUTORS.rst
  MANIFEST.in
  Makefile
  docs/source/conversions.rst
  docs/source/info.rst
  oct2py/core.py
  oct2py/dynamic.py
  oct2py/io.py
  oct2py/ipython/__init__.py
  oct2py/ipython/ipython-COPYING.txt
  oct2py/ipython/octavemagic.py
  oct2py/ipython/tests/test_octavemagic.py
  oct2py/tests/test_misc.py
  setup.cfg
Labels: maintenance

#225 Fix column vector
  oct2py/io.py
  oct2py/tests/test_conversions.py
Labels: bug

#229 Automated Changelog Entry for 5.5.0 on main
  CHANGELOG.md
Labels: documentation

#232 Run AutoFormatters
  .github/workflows/tests.yml
  .pre-commit-config.yaml
  CHANGELOG.md
  CONTRIBUTING.rst
  docs/_templates/layout.html
  docs/environment.yml
  docs/source/api.rst
  docs/source/conf.py
  docs/source/conversions.rst
  docs/source/demo.rst
  docs/source/examples.rst
  docs/source/index.rst
  docs/source/installation.rst
  example/roundtrip.py
  example/test_datatypes.m
  example/test_datatypes.py
  licenses/octavemagic.txt
  oct2py/__init__.py
  oct2py/_version.py
  oct2py/compat.py
  oct2py/core.py
  oct2py/demo.py
  oct2py/dynamic.py
  oct2py/io.py
  oct2py/ipython/octavemagic.py
  oct2py/ipython/tests/test_octavemagic.py
  oct2py/speed_check.py
  oct2py/tests/pyeval_like_error0.m
  oct2py/tests/pyeval_like_error1.m
  oct2py/tests/pyeval_like_error2.m
  oct2py/tests/pyeval_like_error3.m
  oct2py/tests/test_conversions.py
  oct2py/tests/test_misc.py
  oct2py/tests/test_numpy.py
  oct2py/tests/test_roundtrip.py
  oct2py/tests/test_usage.py
  oct2py/thread_check.py
  oct2py/utils.py
  readthedocs.yml
  setup.py
Labels: maintenance

#233 Add flake8 and remove py2 compat
  .pre-commit-config.yaml
  docs/source/conf.py
  oct2py/compat.py
  oct2py/core.py
  oct2py/demo.py
  oct2py/dynamic.py
  oct2py/io.py
  oct2py/ipython/__init__.py
  oct2py/ipython/octavemagic.py
  oct2py/ipython/tests/test_octavemagic.py
  oct2py/tests/test_conversions.py
  oct2py/tests/test_misc.py
  oct2py/tests/test_roundtrip.py
  oct2py/tests/test_usage.py
  oct2py/thread_check.py
  oct2py/utils.py
  setup.cfg
Labels: maintenance

#234 Switch to flit backend
  .coveragerc
  .flake8
  .git-blame-ignore-revs
  .github/workflows/tests.yml
  .readthedocs.yml
  MANIFEST.in
  Makefile
  docs/environment.yml
  docs/source/conf.py
  oct2py/_version.py
  oct2py/core.py
  oct2py/utils.py
  pyproject.toml
  readthedocs.yml
  setup.cfg
  setup.py
Labels: maintenance
