Repository blink1073/oct2py, pull requests merged in 2022-01, with the labels that each got.

#202 Update for latest octave_kernel
  .github/workflows/check-release.yml
  .github/workflows/tests.yml
  Makefile
  README.rst
  docs/source/examples.rst
  docs/source/info.rst
  example/octavemagic_extension.ipynb
  oct2py/ipython/octavemagic.py
  pyproject.toml
  setup.cfg
Labels: enhancement

#204 Automated Changelog Entry for 5.4.0 on main
  CHANGELOG.md
Labels: documentation

#205 Fix setup fields
  setup.cfg
Labels: bug

#206 Automated Changelog Entry for 5.4.1 on main
  CHANGELOG.md
Labels: documentation

#208 Clean up handling of nout in feval
  oct2py/core.py
Labels: bug

#209 add _print_doc
  oct2py/core.py
Labels: enhancement

#210 Automated Changelog Entry for 5.4.2 on main
  CHANGELOG.md
Labels: documentation

#213 Clean up CI
  .github/workflows/check-release.yml
  .github/workflows/tests.yml
Labels: maintenance

#216 Clean up plot dir handling
  oct2py/ipython/octavemagic.py
Labels: bug

#217 Automated Changelog Entry for 5.4.3 on main
  CHANGELOG.md
Labels: documentation
